# Generated by Django 2.2.7 on 2019-12-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civiljobs',
            name='user_it',
        ),
        migrations.RemoveField(
            model_name='itjobs',
            name='user_it',
        ),
        migrations.RemoveField(
            model_name='mechjobs',
            name='user_it',
        ),
    ]
