# Generated by Django 2.2.7 on 2019-12-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
        ('Firstapp', '0002_auto_20191218_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='civiljobs',
            name='user_it',
            field=models.ManyToManyField(default=False, to='Userapp.UserReg'),
        ),
        migrations.AddField(
            model_name='itjobs',
            name='user_it',
            field=models.ManyToManyField(default=False, to='Userapp.UserReg'),
        ),
        migrations.AddField(
            model_name='mechjobs',
            name='user_it',
            field=models.ManyToManyField(default=False, to='Userapp.UserReg'),
        ),
    ]
