# Generated by Django 2.2.7 on 2019-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='privatejob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Padd1', models.TextField()),
                ('Padd2', models.TextField()),
                ('Padd3', models.TextField()),
                ('Padd4', models.TextField()),
                ('Padd5', models.TextField()),
                ('Padd6', models.TextField()),
            ],
        ),
    ]
