# Generated by Django 2.2.7 on 2019-12-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatejob',
            old_name='Padd1',
            new_name='padd1',
        ),
        migrations.RenameField(
            model_name='privatejob',
            old_name='Padd2',
            new_name='padd2',
        ),
        migrations.RenameField(
            model_name='privatejob',
            old_name='Padd3',
            new_name='padd3',
        ),
        migrations.RenameField(
            model_name='privatejob',
            old_name='Padd4',
            new_name='padd4',
        ),
        migrations.RenameField(
            model_name='privatejob',
            old_name='Padd5',
            new_name='padd5',
        ),
        migrations.RenameField(
            model_name='privatejob',
            old_name='Padd6',
            new_name='padd6',
        ),
    ]
