# Generated by Django 2.2.7 on 2019-12-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Postapp', '0002_auto_20191216_1727'),
        ('Userapp', '0002_auto_20191216_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentbox', models.TextField(blank=True, null='')),
                ('cfileupload', models.FileField(blank=True, null='', upload_to='FileUpload/')),
                ('commentforpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Postapp.Post')),
                ('commentforuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.User')),
            ],
        ),
    ]
