# Generated by Django 2.2.7 on 2019-12-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentforuser',
            new_name='commentbyuser',
        ),
    ]
