# Generated by Django 2.2.7 on 2019-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Average', models.CharField(max_length=30)),
            ],
        ),
    ]
