# Generated by Django 2.2.7 on 2019-11-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('ecom', models.CharField(max_length=30)),
                ('esal', models.IntegerField()),
                ('eaddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=20)),
                ('employee', models.ManyToManyField(to='Firstapp.Employee')),
            ],
        ),
    ]
