# Generated by Django 2.2.7 on 2019-11-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
