# Generated by Django 2.2.7 on 2020-01-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='Username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
