# Generated by Django 2.2.7 on 2019-12-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.TextField()),
                ('Brand', models.TextField()),
                ('Price', models.IntegerField()),
                ('Ram', models.TextField()),
            ],
        ),
    ]
