# Generated by Django 2.2.7 on 2019-12-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Mname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Ram',
            field=models.CharField(max_length=30),
        ),
    ]
