# Generated by Django 2.2.7 on 2019-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Company', models.TextField()),
                ('Salary', models.IntegerField()),
                ('Experience', models.FloatField()),
            ],
        ),
    ]
