# Generated by Django 2.2.7 on 2019-12-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userapp', '0002_auto_20191216_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('ptag', models.TextField()),
                ('fileupload', models.FileField(null=True, upload_to='FileUpload/')),
                ('postbyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.User')),
            ],
        ),
    ]
