# Generated by Django 2.2.7 on 2019-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fileupload',
            field=models.FileField(blank=True, null='', upload_to='FileUpload/'),
        ),
    ]
