# Generated by Django 2.2.7 on 2019-12-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postapp', '0002_auto_20191216_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fileupload',
            field=models.FileField(blank=True, null='', upload_to=''),
        ),
    ]
