# Generated by Django 2.2.7 on 2019-12-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postapp', '0003_auto_20191223_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fileupload',
            field=models.FileField(blank=True, null='', upload_to='FileUpload/'),
        ),
    ]
